version: '3.1'

services:
  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  backend:
    build: ./backend
    command: python /code/manage.py rundebugserver 0.0.0.0:80
    volumes:
      - ./backend:/code:delegated
    ports:
      - "8000:80"
      - "9000:9000"
    links:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgres://postgres@db:5432/postgres'
      ENVIRONMENT: 'development'

networks:
  default:
    ipam:
      config:
        - subnet: 172.16.132.0/24
